### PR TITLE
Add separate network request queue to avoid deadlock. Minor refactor.

### LINKED ISSUE #190: Fix possible deadlock
When scheduling `BUYRequestOperation`s and network requests on the same queue, it possible that they'll wait on each other indefinitely if the queue doesn't support enough concurrent operations.

Solution is to use two separate queue for operations and network requests.

### PR DESCRIPTION
**Pull request by dbart01**
### What this does
- adds a separate, private network queue for `NSURLSessionDataTask` requests
- minor refactoring and cleanup

Fixes #190 

@bgulanowski @davidmuzi

### CODE REVIEW

**Comment by davidmuzi** [comment]
The queue used for the NSURLSession is not a queue for the network request to execute on, its the queue where the callbacks are called from.  This queue is intended to be public so the caller can have them scheduled on the queue of their choosing.

> An operation queue for scheduling the delegate calls and completion handlers. The queue need not be a serial queue. If nil, the session creates a serial operation queue for performing all delegate method calls and completion handler calls.

**Comment by dbart01** [comment]
The `NSURLSession`'s `delegateQueue` is used for callbacks, that's true. However, it's also used for network requests' delegate method calls of the `NSURLSession`. Since `NSURLSession` is now an internal implementation detail, I feel that the `delegateQueue` should also remain internal. In addition, the `delegateQueue` cannot be set after `NSURLSession` initialization. The user can set the `requestQueue` to whatever they and that will ensure that callbacks are executed on that queue.

**Comment by dbart01** [comment]
> Why not pass in nil?
We could. In that case `NSURLSession` will default to a serial queue. I thought the SDK might benefit from an explicit concurrent queue. The decision is up for debate.

**Comment by bgulanowski** [comment]
The naming is confusing. And I think the extra queue is unnecessary.

There are two levels of callback: the client's, and the app's. The client's callbacks should run in the background on a private, concurrent queue. I don't see why that queue is exposed. If that queue is concurrent, request operations should be able to run there, too. Where is the risk of deadlocks coming from?

The app's callbacks should happen on whatever queue the app specifies, by default the main queue. That is the queue that should be exposed.

**Comment by dbart01** [comment]
The queues are not just used for callbacks. We need three queues:
- queue owned and managed by `NSURLSession` for handling delegate callbacks AND completion callback
- queue that will enqueue `BUYRequestOperation`s. This should be a different queue than the `NSURLSession` queue to avoid a deadlock situation where the operation kicks off a request scheduled on the same queue as the operation. In that case, the callback from the session will be waiting on the operation, which is waiting on the callback.
- finally, we have a "convenience" queue that schedules user-level callbacks, by default on the main thread

On second though, we don't need to expose the first two queue. Just the last one.

**Comment by davidmuzi** [comment]
In that case, you would need one private queue to enqueue the BUYRequestOperations, a public queue for callbacks which defaults to mainQueue, and pass in nil for the NSURLSession callbacks, and have that use its own serial queue - there is no need for concurrency.

**Comment by dbart01** [comment]
That's fine with me.

**Pull request merged**
