### PR TITLE
Update schema.

### PR DESCRIPTION
**Pull request by jmignac**
Update schema (auto-generated)

### CODE REVIEW

**Comment by dbart01** [comment]
Please rebase on latest `develop`.

**Comment by rebeccajfriedman** [comment]
Can you look into the test failures please?

**Comment by rebeccajfriedman** [comment]
Was this made redundant by #1001 ? Should this be closed?

**Comment by jmignac** [comment]
Replaced by https://github.com/Shopify/mobile-buy-sdk-ios/pull/1000

**Pull request closed without merging**
