### PR TITLE
Update ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by RishabhTayal**
### What this does

typo fix

### CODE REVIEW

**Comment by dbart01** [comment]
Could you please rebase on `develop`?

**Comment by RishabhTayal** [comment]
@dbart01 done

**Comment by dbart01** [comment]
Please rebase, don't merge. The above change log should contain a single commit to update `ISSUE_TEMPLATE.md`.

**Comment by RishabhTayal** [comment]
Closed this in favor of #985

**Pull request closed without merging**
