### PR TITLE
updated README.md

### LINKED ISSUE #1023: Update checkoutWithCreditCard documentation
The current README.md documentation uses V1 of `checkoutCompleteWithCreditCard` mutation. It would be nice to update it to `checkoutCompleteWithCreditCardV2`.

### PR DESCRIPTION
**Pull request by RishabhTayal**
### What this does

changed checkoutCompleteWithCreditCard to checkoutCompleteWithCreditCardV2

Fixes #1023

### CODE REVIEW

**Comment by dbart01** [comment]
Could you please rebase on `develop`?

**Comment by RishabhTayal** [comment]
@dbart01 done.

> Could you please rebase on `develop`?

**Comment by dbart01** [comment]
This branch still includes unnecessary commits. Please rebase and remove all commits except the one that modifies the README.

**Comment by RishabhTayal** [comment]
@dbart01 I am closing this PR in favor of #1026

**Pull request closed without merging**
