### PR TITLE
Adds deleted View Controllers to Advanced Sample App

### PR DESCRIPTION
**Pull request by gabrieloc**
@dbart01 pointed out the classes removed in https://github.com/Shopify/mobile-buy-sdk-ios/pull/172 are still being used by the Advanced Sample App. This change re-adds them.

@davidmuzi

### CODE REVIEW

**Comment by dbart01** [comment]
Missing `.h` header files.

**Comment by davidmuzi** [comment]
Is this changing anything?

Adding files to a folder won't change anything if they are not used by a project and included in their .xcproject.

**Comment by dbart01** [comment]
Yes, they should be included in the project file of the sample app.

**Comment by gabrieloc** [comment]
@davidmuzi Those classes were actually outdated, and have since been renamed and copied into the sample app project. I've reversed the original commit.

As well, I've cleaned up duplication and naming:
- `UIFont`/`UIImage` categories existed 3 times, once in `UIKitAdditions/`, once in `Utils/`, and once in `Library/`. I've removed all but the classes in `Utils/`.
- ProductView-related classes have been moved into `Product View` folder
- Classes prefixed with `BUY` have had the `BUY` removed

**Comment by dbart01** [comment]
LGTM 🎩

**Pull request merged**
