### PR TITLE
Add Customer Sample App README.md

### PR DESCRIPTION
**Pull request by dbart01**
### What this is

We'll need a readme file for the customer sample app. This adds one.

@bgulanowski @davidmuzi

### CODE REVIEW

**Comment by davidmuzi** [comment]
Are we going to have a more descriptive integration guide for using the Customer API?  There are nuances that should be documented such as storing the customer token, handing token refreshing, and handling password reset and account activation in-app, for instance.

**Comment by bgulanowski** [comment]
There is an issue here: https://github.com/Shopify/mobile-buy-sdk-ios/issues/143

**Comment by dbart01** [comment]
As @bgulanowski mentioned, there will be a separate guide. Since these nuances aren't showcased in the sample app, its best that the readme reflects that, in my opinion.

**Comment by bgulanowski** [comment]
👍

**Pull request merged**
