### PR TITLE
Remove code from sample app that is not used

### PR DESCRIPTION
**Pull request by bgulanowski**
Left over from the updates for 2.0.

@davidmuzi @gabrieloc

### CODE REVIEW

**Comment by gabrieloc** [comment]
I dont understand how that code isn't needed. Should it be exercised?

**Comment by bgulanowski** [comment]
The product view controller configures those buttons itself, including setting their labels and actions. The wrapper wasn't really adding anything, and it was inconsistent, because the abstraction (of the buttons) was incomplete.

**Comment by bgulanowski** [comment]
Could cherry pick this into `release/2.0.1`.

**Comment by davidmuzi** [comment]
🚢

**Pull request merged**
