### PR TITLE
Feature: fetch all pages

### PR DESCRIPTION
**Pull request by bgulanowski**
Convenience for getting everything. Observable. Cancellable.

Support for collections, products, and tags.

⚠️   Use with caution! ⚠️ 

@davidmuzi @gabrieloc

### CODE REVIEW

**Comment by davidmuzi** [comment]
Do we need this? What about Android?

**Comment by krisorr** [comment]
@davidmuzi no, I don't think we need it. I would be hesitant to add this to the sdk.

**Comment by gabrieloc** [comment]
We need proper pagination support instead

**Comment by bgulanowski** [comment]
How do we feel about making the operation classes public?

**Comment by pwr7549** [comment]
We need to fetch all products and collections. If we collect these product_types, we will be able to create a list of product_types at the opening on Apple TV. We also could call the certain collections or products by a specified product_type.

**Comment by bgulanowski** [comment]
@pwr7549 please add a github story, and we can label it as an enhancement request.

**Pull request closed without merging**
