### PR TITLE
Add tvOS support for SDK 2.0

### LINKED ISSUE #384: tvOS support
Add a new target to the SDK to build the framework for tvOS.

The framework should still be named "Buy".

### PR DESCRIPTION
**Pull request by gabrieloc**
## What this does

Adds a tvOS framework target and refactors certain files to not use framework imports.

Resolves #384

@bgulanowski @davidmuzi @dbart01

### CODE REVIEW

**Comment by davidmuzi** [comment]
Why can't you use framework imports?
should point to develop

**Comment by bgulanowski** [comment]
@davidmuzi  Different framework names.

We should, I have just realized, instead use the same framework (product) name, which doesn't have to match the target name. It shouldn't affect build environment, since products for different platforms are placed into different build folders. (Should be built in "tvos-debug" or "tvos-release" folder.)

**Comment by bgulanowski** [comment]
@gabrieloc  If we can rename the product to still be "Buy", we don't have to change the headers or imports. (Target will still be "BuyTV".)

**Comment by bgulanowski** [comment]
Try rebasing this on `develop`.

**Comment by pwr7549** [comment]
Hello, I am looking forward to get that completion of BuyTV for our retailing app.

**Comment by gabrieloc** [comment]
This branch has been rebased onto `develop`. Mergability?

**Comment by bgulanowski** [comment]
No, we can't merge this.

- [ ] The framework must still be named `Buy`, not `BuyTV`. The target and product name don't have to match.
- [ ] remove duplicate umbrella header (and another other duplicate files)

**Comment by pwr7549** [comment]
is this Buy framework ready made for TVOS ?

**Comment by bgulanowski** [comment]
@pwr7549  I don't understand your question.

**Comment by pwr7549** [comment]
Will I be able to use Buy framework to be complied into TVOS just after you had committed the coding into GitHub repository today?

**Comment by bgulanowski** [comment]
You are free to try. Obviously we make no promises and offer no guarantees. Open source rules apply.

**Comment by EishanVijay** [comment]
Going to close off this PR and create a new one to support tvOS

**Pull request closed without merging**
